name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        echo Installing package ...
        python setup.py install
        echo SyferTest successfully installed.
        echo Running tests ...
	python -m pytest
