name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: '>=3.6'
    - name: Install SyferText
      run: |
        python setup.py install
        echo SyferTest successfully installed.
    - name: Running tests
      run: |    
        python -m pytest tests --black --verbose

